### PR TITLE
Msg externalization class with factory (/static) methods.

### PR DESCRIPTION
**Pull request by tarilabs**
Clean-up os SLF4J logging now not-required

### CODE REVIEW

**Comment by tarilabs** [comment]
@etirelli if the `Msg` class is okay, I can extend this approach to the rest of the packages. What do you think?

**Comment by manstis** [comment]
Is a static method factory desirable? It shuts the door to overriding. Perhaps the static factory could be a bridge to the real provider that we could set on the factory (or use a default)?

**Comment by tarilabs** [comment]
I'm not sure I'm following 100%, let's double check, accordingly to current proposal to modify by:

```
class Msg {
private Msg() { }

// new "instance" method
public static Msg msg() { return new Msg(); }
}
```

and then have all the current methods as instance methods?

**Comment by manstis** [comment]
Oh, I was thinking more like:-
```
class Msg {

    interface MessageProvider {
        String baseNodeEvaluateCalled();
    }

    private static MessageProvider provider = new MessageProvider() {

        private static final String BASE_NODE_EVALUATE_CALLED = "BaseNode evaluate called";

        public String baseNodeEvaluateCalled() {
            return BASE_NODE_EVALUATE_CALLED;
        }

    }

    public static String baseNodeEvaluateCalled() {
        return provider.baseNodeEvaluateCalled();
    }

    public void setMessageProvider( final MessageProvider provider ) {
        this.provider = provider;
    }

}
```

**Comment by etirelli** [comment]
@manstis the goal of this particular class is to centralize all the message strings in a single place so that they can be easily i18n later... I see no problem with your suggestion other than it being more work for a very simple case like this, but you are the tools expert... do you think there would be any benefit in making a provider for this?

**Comment by etirelli** [comment]
Looks good now @tarilabs . Should I merge?

**Comment by tarilabs** [comment]
@etirelli just double-check all tests passing locally, for me yes, we can always improve or refactor later if we need. 

About @manstis 's proposal I can somehow understand what is the ultimate goal, but the actual approach suggested would force to have the provider statically chosen across the JVM, so I'm still not 100% sure what would be the benefit there? Anyway, we can include @manstis 's suggestion later, for now we achieved having the "keys" as public static fields which I understand is a reached common agreement.

**Comment by etirelli** [comment]
Merged.

**Pull request merged**
