### PR TITLE
Number coercion to BigDecimal for EvaluationContext

### PR DESCRIPTION
**Pull request by tarilabs**

### CODE REVIEW

**Comment by tarilabs** [comment]
@etirelli this is my proposal for number coercion to BigDecimal, but I have a doubt, please?

Originally I started modifying the InfixOpNode as starting point as discussed, for instance:
```
    private Object comparison(Object left, Object right, EvaluationContext ctx, BiPredicate<Comparable, Comparable> op) {
        if ( left == null || right == null ) {
            return null;
        } else if ( (left instanceof String && right instanceof String) ||
                    (left instanceof Number && right instanceof Number) ||
                    (left instanceof Boolean && right instanceof Boolean) ||
                    (left instanceof Comparable && left.getClass().isAssignableFrom( right.getClass() )) ) {
            Comparable l = (Comparable) ( left  instanceof Number ? EvalHelper.getBigDecimalOrNull( left  ) : left  );
            Comparable r = (Comparable) ( right instanceof Number ? EvalHelper.getBigDecimalOrNull( right ) : right );
            return op.test( l, r );
        }
        return null;
    }
```

Yet I realized this appears not necessary, neither to modify the `CompilerContext`, but to me should be enough to modify the `EvaluationContextImpl` as per this PR proposal.

I have added a few test also to check tricky cases, but all looks working to me.

Yet, I'm always doubtful when the solution appears "too simple" :) can we discuss this proposal, please?

**Comment by etirelli** [comment]
@tarilabs your proposal here fixes the case where the variable is the root value set on the context, but what happens when the variable is a property in an object, or a nested value in a Map? In those cases you can't change the type of the value, and so I believe we still need to change the InfixOpNode (and possibly other places) to deal with the different number types... :(

**Comment by tarilabs** [comment]
Extended to cover the case "when the variable is a property in an object, or a nested value in a Map" as discussed.

**Comment by etirelli** [comment]
@tarilabs looks good, thanks! The only thing is it would be best to remove the System.out from the test, but we can do that later. Can I go ahead and merge this?

**Comment by tarilabs** [comment]
Please go ahead for the merge.

Sorry I missed a sysout, in those cases using slf4j logging is fine for the test output, correct?
I will keep in mind going ahead.

**Comment by etirelli** [comment]
I actually prefer to not have any additional output on tests once they are working (it is fine during development), but this is not strictly enforced. In any case, a logger is better than a system.out as we can control the log and redirect to make the console output cleaner. (I am nitpicking here... :))

**Pull request merged**
